name: 文件传递示例

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 生成文件
        run: echo "这是 job1 生成的文件内容" > generated-file.txt

      - name: 传递文件
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: generated-file.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 下载文件
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: 显示文件内容
        run: cat generated-file.txt
